print("\t================================")
print()
print("\tHi! WELCOME TO CHIJULYBUILDS CALCULATOR")
print()
print("\t================================")
print()
print("Welcome to your one smart calculator!!")
print()
print("From now on, you can use this calculator to do all your calculations ranging from", "Basic Arithmetic Operations and other operations like", sep="-")
print()
print("\tAddition(+)")
print("\tSubtraction(-)")
print("\tMultiplication(*)")
print("\tDivision(/)")
print("\tExponentiation(**)")
print("\tFloor Division(//)")
print("\tModulus(%)")
print()
print("One thing that stands out for you as a user of the chijulybuilds caclulator is having the ability to solve operators found in paraenthesis in an equation.")
print()
print("Some arithmetic problems solved are,")
print("\tFor Addition: 13 + 6", 13 + 6, sep=" = ")
print("\tFor Subtraction: 14 - 13.", 14 - 13., sep=" = ")
print("\tFor Multiplication: 3. * 7", 3. * 7, sep=" = ")
print("\tFor Division: 16 / 3", 16 / 3, sep=" = ")
print("\tFor Exponentiation: 3. ** 4 ** 2", 3 ** 4 ** 2, sep=" = ")
print("\t\"Note: Exponentiation follows the right-sided binding\"")
print("\tFor Floor Division: -7e9 // 3e5", -7e9 // 3e5, sep=" = ")
print("\tFor Modulus: 16.3 % 7 % 4", 16.3 % 7 % 4, sep=" = ")
print("\tFor Parenthesis: (15 * ((45 % 2) - 36) / (3 * 5) // 4)", (15 * ((45 % 2) - 36) / (3 * 5) // 4), sep=" = ")
print()
print("====== PRESS \"AC\" TO CLEAR THE CALCULATOR =====")
print()
print("====== PRESS \"EXIT\" TO EXIT THE CALCULATOR =====")
print()
print("This calculator was built by Chijulybuilds, a python developer and enthusiast!")
print()
print("\t\tGOODLUCK!")